name: Update ChatGPT Context
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (npm fallback)
        run: npm ci || npm i

      - name: Generate snapshot
        run: npx tsx tools/chatgpt-context.ts

      # ---- Diagnostics so we see exactly what's wrong (no secrets printed) ----
      - name: Check secrets exist
        run: |
          if [ -z "${{ secrets.GIST_ID }}" ]; then echo "GIST_ID is MISSING"; exit 1; else echo "GIST_ID is present"; fi
          if [ -z "${{ secrets.GIST_TOKEN }}" ]; then echo "GIST_TOKEN is MISSING"; exit 1; else echo "GIST_TOKEN is present"; fi
          test -f .chatgpt/chatgpt-context.md || (echo "snapshot file missing"; exit 1)

      # ---- Update Gist (simple, reliable) ----
      - name: Update Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}          # PAT with gist scope
          gist_id: ${{ secrets.GIST_ID }}           # e.g. 51ed72896ed154e274ce17f4a7093937
          file_path: .chatgpt/chatgpt-context.md    # local file
          file_type: text/markdown                  # content type

      # Always upload artifact for debugging
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatgpt-context
          path: .chatgpt/chatgpt-context.md
