name: Update ChatGPT Context

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  # run from Actions UI

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (npm fallback)
        run: npm ci || npm i

      - name: Generate snapshot
        run: npx tsx tools/chatgpt-context.ts

      - name: Install jq (if missing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Debug secrets presence
        run: |
          if [ -z "${{ secrets.GIST_ID }}" ]; then
            echo "GIST_ID is NOT set"
          else
            echo "GIST_ID is set"
          fi

          if [ -z "${{ secrets.GIST_TOKEN }}" ]; then
            echo "GIST_TOKEN is NOT set"
          else
            echo "GIST_TOKEN is set"
          fi

      - name: Update Gist via API
        if: ${{ secrets.GIST_ID && secrets.GIST_TOKEN }}
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          set -euo pipefail
          FILE=".chatgpt/chatgpt-context.md"
          if [ ! -f "$FILE" ]; then
            echo "Snapshot not found: $FILE"
            exit 1
          fi
          # Encode file content as JSON string safely
          CONTENT=$(jq -Rsa . < "$FILE")
          PAYLOAD=$(jq -n --arg c "$CONTENT" '{files: {"abot-ko-na-context.md": {content: $c}}}')

          echo "Patching Gist $GIST_ID..."
          HTTP_STATUS=$(curl -sS -w "%{http_code}" -o /tmp/gist_resp.json \
            -X PATCH "https://api.github.com/gists/${GIST_ID}" \
            -H "Authorization: Bearer ${GIST_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            -d "$PAYLOAD")

          echo "HTTP status: $HTTP_STATUS"
          echo "Response:"
          cat /tmp/gist_resp.json

          test "$HTTP_STATUS" = "200" || exit 1

      - name: Upload artifact (fallback if no secrets)
        uses: actions/upload-artifact@v4
        with:
          name: chatgpt-context
          path: .chatgpt/chatgpt-context.md
